# Generated by Django 4.2.30 on 2026-04-17 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BibleVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('language', models.CharField(default='English', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('abbreviation', models.CharField(max_length=10)),
                ('testament', models.CharField(choices=[('OT', 'Old Testament'), ('NT', 'New Testament')], max_length=3)),
                ('order', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Verse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.PositiveSmallIntegerField()),
                ('verse_number', models.PositiveSmallIntegerField()),
                ('text', models.TextField()),
                ('normalized_text', models.TextField(blank=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verses', to='bible.book')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verses', to='bible.bibleversion')),
            ],
        ),
        migrations.CreateModel(
            name='SavedVerse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40)),
                ('note', models.TextField(blank=True)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('verse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bible.verse')),
            ],
            options={
                'ordering': ['-saved_at'],
            },
        ),
        migrations.AddIndex(
            model_name='verse',
            index=models.Index(fields=['version', 'book', 'chapter'], name='bible_verse_version_a596e8_idx'),
        ),
        migrations.AddIndex(
            model_name='verse',
            index=models.Index(fields=['normalized_text'], name='bible_verse_normali_82d895_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='verse',
            unique_together={('version', 'book', 'chapter', 'verse_number')},
        ),
    ]
